.TH "ca.mcgill.ecse211.tests.ComponentTest" 3 "Wed Nov 28 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.tests.ComponentTest
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBType\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBrunTest\fP (\fBType\fP testType)  throws Exception "
.br
.ti -1c
.RI "static void \fBnavigationTest\fP ()  throws OdometerExceptions "
.br
.ti -1c
.RI "static void \fBtunnelTest\fP ()  throws Exception "
.br
.ti -1c
.RI "static void \fBlocalizationTest\fP ()  throws OdometerExceptions "
.br
.ti -1c
.RI "static void \fBultrasonicSensorTest\fP ()"
.br
.ti -1c
.RI "static void \fBlightSensorTest\fP ()"
.br
.ti -1c
.RI "static void \fBringMotorTest\fP ()  throws OdometerExceptions "
.br
.ti -1c
.RI "static void \fBblackLineTest\fP ()  throws OdometerExceptions "
.br
.ti -1c
.RI "static void \fBmusicTest\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This singleton contains all the methods and structures necessary to test our robot and its components
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro 
.PP
Percy Chen 
.PP
Patrick Erath 
.PP
Anssam Ghezala 
.PP
Susan Matuszewski 
.PP
Kamy Moussavi Kafi 
.RE
.PP

.PP
Definition at line 25 of file ComponentTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.blackLineTest () throws \fBOdometerExceptions\fP\fC [static]\fP"

.PP
Definition at line 147 of file ComponentTest\&.java\&.
.PP
.nf
147                                                                {
148     Navigation navi = new Navigation(Game\&.leftMotor, Game\&.rightMotor);
149     GameUtil\&.searchingFinder =
150         new GameUtil\&.PathFinder(GameParameters\&.Island_LL, GameParameters\&.Island_UR);
151     int[] arr1 = {0, 0};
152     int[] arr2 = {0, 0};
153     GameUtil\&.startingFinder = new GameUtil\&.PathFinder(arr1, arr2);
154     int count = 0;
155     while (count < 85) {
156       navi\&.moveOneTileWithCorrection(0);
157       count++;
158       if (count % 7 == 0) {
159         navi\&.turn(90);
160       }
161     }
162   }
.fi
.SS "static void ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.lightSensorTest ()\fC [static]\fP"
Test for lightSensor 
.PP
Definition at line 117 of file ComponentTest\&.java\&.
.PP
.nf
117                                        {
118 
119   }
.fi
.SS "static void ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.localizationTest () throws \fBOdometerExceptions\fP\fC [static]\fP"
Test for localizationTest
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 99 of file ComponentTest\&.java\&.
.PP
.nf
99                                                                   {
100     Navigation navigation = new Navigation(Game\&.leftMotor, Game\&.rightMotor);
101     UltrasonicLocalizer us = new UltrasonicLocalizer(navigation, Game\&.leftMotor, Game\&.rightMotor);
102     LightLocalizer lgLoc = new LightLocalizer(navigation, Game\&.leftMotor, Game\&.rightMotor);
103     us\&.localize(Button\&.ID_LEFT);
104     lgLoc\&.localize(GameParameters\&.SC);
105   }
.fi
.SS "static void ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.musicTest ()\fC [static]\fP"

.PP
Definition at line 164 of file ComponentTest\&.java\&.
.PP
.nf
164                                  {
165     GameUtil\&.playMusic();
166   }
.fi
.SS "static void ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.navigationTest () throws \fBOdometerExceptions\fP\fC [static]\fP"
Test for Navigation
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 70 of file ComponentTest\&.java\&.
.PP
.nf
70                                                                 {
71     Navigation nav = new Navigation(Game\&.leftMotor, Game\&.rightMotor);
72     nav\&.travelToWithCorrection(4, 2, false);
73     nav\&.travelToWithCorrection(0, 0, false);
74     nav\&.travelToWithCorrection(4, 2, false);
75     nav\&.travelToWithCorrection(0, 0, false);
76     nav\&.travelToWithCorrection(4, 2, false);
77     nav\&.travelToWithCorrection(0, 0, false);
78     nav\&.travelToWithCorrection(4, 2, false);
79     nav\&.travelToWithCorrection(0, 0, false);
80     nav\&.travelToWithCorrection(4, 2, false);
81     nav\&.travelToWithCorrection(0, 0, false);
82   }
.fi
.SS "static void ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.ringMotorTest () throws \fBOdometerExceptions\fP\fC [static]\fP"
Test for ring detection
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 126 of file ComponentTest\&.java\&.
.PP
.nf
126                                                                {
127     Game\&.INSTANCE\&.usPoller\&.setStart(false);
128     final RingSearcher searcher = new RingSearcher(Game\&.sensorMotor, Game\&.rodMotor);
129     Navigation navigation = new Navigation(Game\&.leftMotor, Game\&.rightMotor);
130     GameUtil\&.searchingFinder =
131         new GameUtil\&.PathFinder(GameParameters\&.Island_LL, GameParameters\&.Island_UR);
132     GameUtil\&.startingFinder = new GameUtil\&.PathFinder(GameParameters\&.US_LL, GameParameters\&.US_UR);
133     Odometer\&.getOdometer()\&.setXYT(1, 1, 0);
134     int[] tree = {2, 2};
135     int[][] other = {{2, 1}, {3, 2}, {2, 3}, {1, 2}};
136     for (int i = 0; i < 4; i++) {
137       navigation\&.travelToWithCorrection(other[i][0], other[i][1], false);
138       navigation\&.turn(-90);
139       if (i != 3) {
140         navigation\&.searchRingSet(searcher, true, true);
141       } else {
142         navigation\&.searchRingSet(searcher, true, false);
143       }
144     }
145   }
.fi
.SS "static void ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.runTest (\fBType\fP testType) throws Exception\fC [static]\fP"
This method selects test for each individual components of the design
.PP
\fBParameters:\fP
.RS 4
\fItype\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 38 of file ComponentTest\&.java\&.
.PP
.nf
38                                                              {
39     try {
40       switch (testType) {
41         case Navigation:
42           ComponentTest\&.navigationTest();
43           break;
44         case Localization:
45           ComponentTest\&.localizationTest();
46           break;
47         case UltrasonicSensor:
48           ComponentTest\&.ultrasonicSensorTest();
49           break;
50         case LightSensor:
51           ComponentTest\&.lightSensorTest();
52           break;
53         case RingDetection:
54           ComponentTest\&.ringMotorTest();
55           break;
56         default:
57           System\&.out\&.println("Invalid test type selected");
58           break;
59       }
60     } catch (Exception e) {
61       throw e;
62     }
63   }
.fi
.SS "static void ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.tunnelTest () throws Exception\fC [static]\fP"

.PP
Definition at line 84 of file ComponentTest\&.java\&.
.PP
.nf
84                                                    {
85     Navigation navigation = new Navigation(Game\&.leftMotor, Game\&.rightMotor);
86     GameUtil\&.searchingFinder =
87         new GameUtil\&.PathFinder(GameParameters\&.Island_LL, GameParameters\&.Island_UR);
88     GameUtil\&.startingFinder = new GameUtil\&.PathFinder(GameParameters\&.US_LL, GameParameters\&.US_UR);
89     Odometer\&.getOdometer()\&.setXYT(1, 7, 90);
90     navigation\&.goThroughTunnel();
91     navigation\&.goThroughTunnel();
92   }
.fi
.SS "static void ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.ultrasonicSensorTest ()\fC [static]\fP"
Test for UltrasonicSensor 
.PP
Definition at line 110 of file ComponentTest\&.java\&.
.PP
.nf
110                                             {
111 
112   }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
